#!/bin/bash
yum update -y 
wget http://dev.mysql.com/get/mysql157-community-release-el7-8.noarch.rpm
yum localinstall -y mysql157-community-release-el7-8.noarch.rpm
yum install -y mysql-community-server
yum install -y httpd php php-mysqlnd git
cd /var/www/html
wget https://wordpress.org/wordpress-5.1.1.tar.gz
tar -xzf wordpress-5.1.1.tar.gz
cp -r wordpress/* /var/www/html/
rm -rf wordpress
rm -rf wordpress-5.1.1.tar.gz
groupadd www
usermod -aG www ec2-user
chown -R root:www /var/www
chmod -R 2775 /var/www
echo '<?php phpinfo(): ?>' > /var/www/html/phpinfo.php
service httpd start
chkconfig httpd on
service mysqld start
systemctl enable mysqld.service
chkconfig mysqld on
